Server:
    port: 8080
Spring:
    main:
        web-application-type: servlet
    application:
        name: user
    datasource:
        password: zhaoxing
        url: jdbc:postgresql://localhost:5432/adopteasy
        username: newbieshine
    jpa:
            hibernate:
                ddl-auto: create-drop
            properties:
                hibernate:
                    dialect: org.hibernate.dialect.PostgreSQLDialect
                    format_sql: true
            show-sql: true

#    config:
#        import: optional:secrets.yml
#    mail:
#        host: smtp.gmail.com
#        username: ${CARBONO_USERNAME}
#        password: ${CARBONO_PASSWORD}
#        port: 587
#        properties:
#            mail:
#                smtp:
#                    auth: true
#                    starttls:
#                        enable: true
#    application:
#            name: user
#    datasource:
#        password: zhaoxing
##        url: jdbc:postgresql://18.136.163.9:5432/carbonouser
#        url: jdbc:postgresql://localhost:5432/adopteasyuser
##        username: postgres
#        username: newbieshine
#        #username need to change to postgres when deploying (ec2 is postgres)
#    jpa:
#        hibernate:
#            ddl-auto: create-drop
#        properties:
#            hibernate:
#                dialect: org.hibernate.dialect.PostgreSQLDialect
#                format_sql: true
#        show-sql: true
#eureka:
#    client:
#        service-url:
#            defaultZone: http://18.136.163.9:8761/eureka/
##            defaultZone: http://localhost:8761/eureka/
#        fetch-registry: true
#        register-with-eureka: true
#    instance:
#        prefer-ip-address: true

